const whitelist = [
    '/api/user/login',
    '/api/user/getUserList',
    '/api/user/add',
    '/api/book/getBookList',
    '/api/book/add',
    '/api/book/update',
    '/api/book/del',
    '/api/teach/getTeachList',
    '/api/teach/getCompleteTeachList',
    '/api/teach/add',
    '/api/teach/update',
    '/api/teach/del',
    '/api/chapter/getChapterList',
    '/api/chapter/add',
    '/api/chapter/update',
    '/api/chapter/del',
    '/api/content/getContent',
    '/api/content/add',
    '/api/content/update',
    '/api/comment/getCommentList',
    '/api/comment/add',
    '/api/comment/del',
    '/api/resource/getResourceList',
    '/api/resource/add',
    '/api/resource/agree',
    '/api/resource/reject',
    '/api/upload/**'
]

module.exports = whitelist
